version: '3.8'

services:
  app:
    container_name: ai-artifacts
    build: .
    ports:
      - "3003:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: production
      TZ: Asia/Shanghai
    restart: unless-stopped